<?php
namespace App\Component;

use \Symfony\Component\HttpFoundation\Request as SymfonyRequest;

/**
 * 增强Request类
 * @package App\Component
 */
class Request extends SymfonyRequest
{
    /**
     * 增强Symfony的Request类，这里为了能支持swoole获取fopen('php://input')的代替方式
     * @param bool $asResource
     * @return string
     */
    public function getContent($asResource = false)
    {
        parent::getContent($asResource); // TODO: Change the autogenerated stub

        if (null === $this->content || false === $this->content) {
            $this->content = \Swoole::getInstance()->http->getRequestBody();
        }

        return $this->content;
    }
}